# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

version: 2.1

orbs:
  win: circleci/windows@5.0
  macos: circleci/macos@2.4.0

executors:
  linux-arm64-amazonlinux-2:
    docker:
      - image: amazonlinux:2
    resource_class: arm.large
    working_directory: ~/typedb

  # All builds go on amazon-linux.
  linux-x86_64-amazonlinux-2:
    docker:
      - image: amazonlinux:2
    resource_class: large
    working_directory: ~/typedb

  linux-x86_64-ubuntu-2204:
    docker:
      - image: ubuntu:22.04
    resource_class: large
    working_directory: ~/typedb

  mac-arm64:
    macos:
      xcode: "13.4.1"
    resource_class: macos.m1.medium.gen1
    working_directory: ~/typedb

  win-x86_64:
    resource_class: windows.xlarge
    machine:
      image: windows-server-2022-gui:2024.01.1
    shell: cmd.exe


commands:

  ######################
  # common setup steps #
  ######################

  install-deps-yum:
    parameters:
      bazel-arch:
        type: string
    steps:
      - run: |
          amazon-linux-extras install python3.8 java-openjdk11 -y
          yum install -y git tar gcc gcc-c++ file lsof which procps llvm-devel clang-devel
          curl -OL "https://github.com/bazelbuild/bazelisk/releases/download/v1.17.0/bazelisk-linux-<<parameters.bazel-arch>>"
          mv "bazelisk-linux-<<parameters.bazel-arch>>" /usr/local/bin/bazel
          chmod a+x /usr/local/bin/bazel

  install-deps-apt:
    parameters:
      bazel-arch:
        type: string
    steps:
      - run: |
          apt update -y
          DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends tzdata
          apt install -y curl build-essential git python3 python3-pip default-jre lsof cmake file wget libclang-dev
          curl -OL "https://github.com/bazelbuild/bazelisk/releases/download/v1.17.0/bazelisk-linux-<<parameters.bazel-arch>>"
          mv "bazelisk-linux-<<parameters.bazel-arch>>" /usr/local/bin/bazel
          chmod a+x /usr/local/bin/bazel

  # deploy & test steps
  test-assembly-linux-x86_64:
    steps:
      - run: |
          bazel build //:assemble-typedb-server
          bazel test //tests/assembly:test_assembly --test_output=errors

  deploy-snapshot-unix:
    steps:
      - run: |
          export DEPLOY_ARTIFACT_USERNAME=$REPO_TYPEDB_USERNAME
          export DEPLOY_ARTIFACT_PASSWORD=$REPO_TYPEDB_PASSWORD
          bazel run --jobs=8 --define version=$(git rev-parse HEAD) //:deploy-typedb-server --compilation_mode=opt -- snapshot

  deploy-release-unix:
    steps:
      - run: |
          export DEPLOY_ARTIFACT_USERNAME=$REPO_TYPEDB_USERNAME
          export DEPLOY_ARTIFACT_PASSWORD=$REPO_TYPEDB_PASSWORD
          bazel run --jobs=8 --define version=$(cat VERSION) //:deploy-typedb-server --compilation_mode=opt -- release

jobs:
  # per platform snapshot deployment
  test-deploy-snapshot-linux-x86_64:
    executor: linux-x86_64-amazonlinux-2
    steps:
      - checkout
      - install-deps-yum:
          bazel-arch: amd64
      - test-assembly-linux-x86_64
      - deploy-snapshot-unix

  # per platform release deployment
  test-deploy-release-linux-x86_64:
    executor: linux-x86_64-amazonlinux-2
    steps:
      - checkout
      - install-deps-yum:
          bazel-arch: amd64
      - test-assembly-linux-x86_64
      - deploy-release-unix

  # generic
  release-cleanup:
    executor: linux-x86_64-ubuntu-2204
    steps:
      - checkout
      - run: |
          apt update -y
          apt install -y git
          git push --delete https://$REPO_GITHUB_TOKEN@github.com/typedb/typedb-driver.git $CIRCLE_BRANCH


workflows:
  typedb-snapshot:
    jobs:
      - test-deploy-snapshot-linux-x86_64:
          filters:
            branches:
              only: [ 3.0-dev ]

  release:
    jobs:
      - test-deploy-release-linux-x86_64:
          filters:
            branches:
              only: [ release ]

      - release-cleanup:
          filters:
            branches:
              only: [ release ]
          requires:
            - test-deploy-release-linux-x86_64
