# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

server:
    address: 0.0.0.0:1729
    http-enabled: true
    http-address: 0.0.0.0:8000

    authentication:
        token-expiration-seconds: 5000

    encryption:
        enabled: false
        certificate:
        certificate_key:
        ca-certificate:

storage:
    data-directory: "data"

logging:
    directory: "logs"
